name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: macos-latest

    steps:
      - name: Checkout project.
        uses: actions/checkout@v4
        with:
          repository: Ausreich/PostMortal
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Install ollama.
        run: brew install ollama

      - name: Install the Rust toolchain.
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run project.
        run: cargo run --release
        env:
          RUST_BACKTRACE: full
          GOOGLE_APP_PASSWORD: ${{secrets.GOOGLE_APP_PASSWORD}}
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          START_TIME: ${{env.START_TIME}}