name: Run

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project.
        uses: actions/checkout@v4
        with:
          repository: Ausreich/PostMortal
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Setup ollama.
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh
          echo "$HOME/.ollama/bin" >> $GITHUB_PATH

      - name: Setup toolchain.
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run project.
        run: cargo run --release
        env:
          PASSWORD: ${{secrets.GOOGLE_APP_PASSWORD}}