name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
        with:
          repository: Ausreich/PostMortal
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Set up python.
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install requirements.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run program.
        run: python main.py